export const ADD_EVENT = 'ADD_EVENT';
export const ADDED_EVENT = 'ADDED_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATED_EVENT = 'UPDATED_EVENT';
export const REMOVE_EVENT = 'REMOVE_EVENT';
export const REMOVED_EVENT = 'REMOVED_EVENT';
export const CHANGE_VIEWING_MONTH = 'CHANGE_VIEWING_MONTH';
export const CHANGE_VIEWING_YEAR = 'CHANGE_VIEWING_YEAR';
